telegram:
  token: "<token>"
  target: 1234567890
  username: focus_observer_bot
  intro: "Hi!!"

repo:
  inmemory: false
  datasource:
    url: jdbc:postgresql://<host>/<schema>
    password: <password>
    user: <user>

format:
  columns: 3